# Generated by Django 6.0.7 on 2026-07-31 14:46

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("email_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="accounts_user_set",
                        related_query_name="accounts_user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="accounts_user_set",
                        related_query_name="accounts_user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_joined", "id"],
            },
            managers=[
                ("objects", accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="ClientProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("address", models.TextField(blank=True)),
                (
                    "profile_status",
                    models.CharField(
                        choices=[
                            ("INCOMPLET", "Incomplet"),
                            ("EN_ATTENTE", "En attente"),
                            ("VALIDE", "Valide"),
                            ("REFUSE", "Refuse"),
                            ("EXPIRE", "Expire"),
                        ],
                        default="INCOMPLET",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="ClientDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("CARTE_IDENTITE", "Carte d'identite"),
                            ("PERMIS_CONDUIRE", "Permis de conduire"),
                        ],
                        max_length=30,
                    ),
                ),
                ("document_number", models.CharField(max_length=120)),
                ("file", models.FileField(upload_to="client_documents/")),
                ("expiration_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente"),
                            ("VALIDE", "Valide"),
                            ("REFUSE", "Refuse"),
                            ("EXPIRE", "Expire"),
                        ],
                        default="EN_ATTENTE",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validated_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="accounts.clientprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("CLIENT", "Client"),
                            ("GESTIONNAIRE_COMPTABLE", "Gestionnaire comptable"),
                            ("ADMINISTRATEUR", "Administrateur"),
                            ("MECANICIEN", "Mecanicien"),
                            ("NETTOYEUR", "Nettoyeur"),
                        ],
                        max_length=40,
                        unique=True,
                    ),
                ),
                ("label", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["label"],
                "indexes": [
                    models.Index(fields=["is_active"], name="role_is_active_idx"),
                    models.Index(fields=["created_at"], name="role_created_at_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("code",), name="role_code_unique")
                ],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="accounts.role",
            ),
        ),
        migrations.AddIndex(
            model_name="clientprofile",
            index=models.Index(
                fields=["profile_status"], name="client_profile_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientprofile",
            index=models.Index(
                fields=["created_at"], name="client_profile_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientprofile",
            index=models.Index(
                fields=["updated_at"], name="client_profile_updated_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientdocument",
            index=models.Index(
                fields=["client", "document_type"], name="client_doc_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientdocument",
            index=models.Index(fields=["status"], name="client_doc_status_idx"),
        ),
        migrations.AddIndex(
            model_name="clientdocument",
            index=models.Index(fields=["expiration_date"], name="client_doc_exp_idx"),
        ),
        migrations.AddIndex(
            model_name="clientdocument",
            index=models.Index(fields=["is_active"], name="client_doc_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="clientdocument",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("client", "document_type"),
                name="uniq_active_doc_per_client_type",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["last_name", "first_name"], name="user_name_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["role", "is_active"], name="user_role_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["date_joined"], name="user_joined_idx"),
        ),
    ]
