# Generated by Django 6.0.7 on 2026-07-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="clientdocument",
            name="uniq_active_doc_per_client_type",
        ),
        migrations.RemoveIndex(
            model_name="clientdocument",
            name="client_doc_type_idx",
        ),
        migrations.AddIndex(
            model_name="clientdocument",
            index=models.Index(
                fields=["client", "document_type", "is_active"],
                name="client_doc_active_type_idx",
            ),
        ),
    ]
