# Generated by Django 6.0.7 on 2026-08-03 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reservations", "0001_initial"),
        ("vehicles", "0002_vehicle_vehiclephoto_vehicle_vehicle_status_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Inspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inspection_type",
                    models.CharField(
                        choices=[("INITIAL", "Initial"), ("FINAL", "Final")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("EN_COURS", "En cours"),
                            ("TERMINE", "Termine"),
                            ("ANNULE", "Annule"),
                        ],
                        db_index=True,
                        default="BROUILLON",
                        max_length=20,
                    ),
                ),
                ("mileage", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "energy_level_percent",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("comments", models.TextField(blank=True)),
                ("has_critical_issue", models.BooleanField(default=False)),
                ("critical_issue_description", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_inspections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspections",
                        to="reservations.reservation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Damage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("MINEUR", "Mineur"),
                            ("MODERE", "Modere"),
                            ("MAJEUR", "Majeur"),
                            ("CRITIQUE", "Critique"),
                        ],
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(max_length=120)),
                ("is_new", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SIGNALE", "Signale"),
                            ("A_ANALYSER", "A analyser"),
                            ("CONFIRME", "Confirme"),
                            ("REJETE", "Rejete"),
                            ("RESOLU", "Resolu"),
                        ],
                        db_index=True,
                        default="SIGNALE",
                        max_length=20,
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reported_damages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="damages",
                        to="vehicles.vehicle",
                    ),
                ),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="damages",
                        to="inspections.inspection",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="InspectionPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo_type",
                    models.CharField(
                        choices=[
                            ("AVANT", "Avant"),
                            ("ARRIERE", "Arriere"),
                            ("COTE_GAUCHE", "Cote gauche"),
                            ("COTE_DROIT", "Cote droit"),
                            ("INTERIEUR", "Interieur"),
                            ("TABLEAU_DE_BORD", "Tableau de bord"),
                            ("DOMMAGE", "Dommage"),
                            ("AUTRE", "Autre"),
                        ],
                        max_length=30,
                    ),
                ),
                ("file", models.ImageField(upload_to="inspections/photos/")),
                ("position", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="inspections.inspection",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="inspection",
            index=models.Index(fields=["reservation"], name="insp_reservation_idx"),
        ),
        migrations.AddIndex(
            model_name="inspection",
            index=models.Index(fields=["status"], name="insp_status_idx"),
        ),
        migrations.AddIndex(
            model_name="inspection",
            index=models.Index(fields=["inspection_type"], name="insp_type_idx"),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.UniqueConstraint(
                fields=("reservation", "inspection_type"),
                name="insp_unique_reservation_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("mileage__gte", 0), ("mileage__isnull", True), _connector="OR"
                ),
                name="insp_mileage_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("energy_level_percent__gte", 0),
                        ("energy_level_percent__lte", 100),
                    ),
                    ("energy_level_percent__isnull", True),
                    _connector="OR",
                ),
                name="insp_energy_0_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("completed_at__isnull", True),
                    ("status", "TERMINE"),
                    _connector="OR",
                ),
                name="insp_completed_at_only_when_done",
            ),
        ),
        migrations.AddIndex(
            model_name="damage",
            index=models.Index(fields=["inspection"], name="damage_inspection_idx"),
        ),
        migrations.AddIndex(
            model_name="damage",
            index=models.Index(fields=["vehicle"], name="damage_vehicle_idx"),
        ),
        migrations.AddIndex(
            model_name="damage",
            index=models.Index(fields=["status"], name="damage_status_idx"),
        ),
        migrations.AddIndex(
            model_name="damage",
            index=models.Index(fields=["severity"], name="damage_severity_idx"),
        ),
        migrations.AddConstraint(
            model_name="damage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("estimated_cost__gte", 0),
                    ("estimated_cost__isnull", True),
                    _connector="OR",
                ),
                name="damage_estimated_cost_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="damage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("resolved_at__isnull", True), ("status", "RESOLU"), _connector="OR"
                ),
                name="damage_resolved_at_only_when_resolved",
            ),
        ),
        migrations.AddIndex(
            model_name="inspectionphoto",
            index=models.Index(
                fields=["inspection", "photo_type"], name="insp_photo_type_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="inspectionphoto",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__gte", 0)),
                name="insp_photo_position_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="inspectionphoto",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("photo_type__in", ["DOMMAGE", "AUTRE"]),
                    ("position", 0),
                    _connector="OR",
                ),
                name="insp_photo_single_views_pos0",
            ),
        ),
        migrations.AddConstraint(
            model_name="inspectionphoto",
            constraint=models.UniqueConstraint(
                fields=("inspection", "photo_type", "position"),
                name="insp_photo_unique_type_position",
            ),
        ),
    ]
