# Generated by Django 6.0.7 on 2026-09-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_allow_interieur_positions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damage',
            name='severity',
            field=models.CharField(choices=[('MINEUR', 'Mineur'), ('MODERE', 'Modere'), ('MAJEUR', 'Majeur'), ('CRITIQUE', 'Critique'), ('ACCEPTABLE', 'Acceptable'), ('GRAVE', 'Grave')], max_length=20),
        ),
    ]
