# Generated by Django 6.0.7 on 2026-08-03 20:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="notification",
            name="notif_user_idx",
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="notif_is_read_idx",
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="notif_created_at_idx",
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("ACCOUNT_CREATED", "Account created"),
                    ("EMAIL_VERIFIED", "Email verified"),
                    ("DOCUMENT_UPLOADED", "Document uploaded"),
                    ("DOCUMENT_VALIDATED", "Document validated"),
                    ("DOCUMENT_REJECTED", "Document rejected"),
                    ("RESERVATION_DRAFT_CREATED", "Reservation draft created"),
                    ("RESERVATION_CONFIRMED", "Reservation confirmed"),
                    ("RESERVATION_CANCELLED", "Reservation cancelled"),
                    ("DEPOSIT_AUTHORIZED", "Deposit authorized"),
                    ("PAYMENT_SUCCEEDED", "Payment succeeded"),
                    ("PAYMENT_FAILED", "Payment failed"),
                    (
                        "DEPARTURE_INSPECTION_COMPLETED",
                        "Departure inspection completed",
                    ),
                    ("RETURN_INSPECTION_COMPLETED", "Return inspection completed"),
                    ("DAMAGE_REPORTED", "Damage reported"),
                    ("INTERVENTION_ASSIGNED", "Intervention assigned"),
                    ("INTERVENTION_COMPLETED", "Intervention completed"),
                    ("INVOICE_AVAILABLE", "Invoice available"),
                    ("VEHICLE_REQUIRES_REVIEW", "Vehicle requires review"),
                    ("PASSWORD_CHANGED", "Password changed"),
                    ("PAYMENT_CONFLICT", "Payment conflict"),
                    ("PAYMENT_CANCELED", "Payment canceled"),
                    (
                        "INTERVENTION_COMPLETED_REVIEW_REQUIRED",
                        "Intervention completed (review required)",
                    ),
                ],
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read", "created_at"],
                name="notif_user_read_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["notification_type"], name="notif_type_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["related_object_type", "related_object_id"],
                name="notif_related_obj_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("is_read", False), ("read_at__isnull", True)),
                    models.Q(("is_read", True), ("read_at__isnull", False)),
                    _connector="OR",
                ),
                name="notif_read_state_consistency",
            ),
        ),
    ]
