# Generated by Django 6.0.7 on 2026-09-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ACCOUNT_CREATED', 'Account created'), ('EMAIL_VERIFIED', 'Email verified'), ('DOCUMENT_UPLOADED', 'Document uploaded'), ('DOCUMENT_VALIDATED', 'Document validated'), ('DOCUMENT_REJECTED', 'Document rejected'), ('RESERVATION_DRAFT_CREATED', 'Reservation draft created'), ('RESERVATION_CONFIRMED', 'Reservation confirmed'), ('RESERVATION_CANCELLED', 'Reservation cancelled'), ('DEPOSIT_AUTHORIZED', 'Deposit authorized'), ('PAYMENT_SUCCEEDED', 'Payment succeeded'), ('PAYMENT_FAILED', 'Payment failed'), ('DEPARTURE_INSPECTION_COMPLETED', 'Departure inspection completed'), ('RETURN_INSPECTION_COMPLETED', 'Return inspection completed'), ('DAMAGE_REPORTED', 'Damage reported'), ('INTERVENTION_ASSIGNED', 'Intervention assigned'), ('INTERVENTION_COMPLETED', 'Intervention completed'), ('INVOICE_AVAILABLE', 'Invoice available'), ('VEHICLE_REQUIRES_REVIEW', 'Vehicle requires review'), ('RESERVATION_REASSIGNMENT_REQUIRED', 'Reservation reassignment required'), ('RESERVATION_REASSIGNED', 'Reservation reassigned'), ('PASSWORD_CHANGED', 'Password changed'), ('PAYMENT_CONFLICT', 'Payment conflict'), ('PAYMENT_CANCELED', 'Payment canceled'), ('INTERVENTION_COMPLETED_REVIEW_REQUIRED', 'Intervention completed (review required)')], max_length=50),
        ),
    ]
