# Generated by Django 6.0.7 on 2026-08-01 00:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="vehicle_brand_name_idx"),
                    models.Index(fields=["is_active"], name="vehicle_brand_active_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Parking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("address", models.TextField()),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-90")),
                            django.core.validators.MaxValueValidator(Decimal("90")),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-180")),
                            django.core.validators.MaxValueValidator(Decimal("180")),
                        ],
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="parking_name_idx"),
                    models.Index(fields=["is_active"], name="parking_active_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("capacity__gt", 0)),
                        name="parking_capacity_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("latitude__isnull", True),
                            models.Q(("latitude__gte", -90), ("latitude__lte", 90)),
                            _connector="OR",
                        ),
                        name="parking_latitude_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("longitude__isnull", True),
                            models.Q(("longitude__gte", -180), ("longitude__lte", 180)),
                            _connector="OR",
                        ),
                        name="parking_longitude_range",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VehicleCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "daily_rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "minimum_deposit",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("minimum_rental_hours", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="vehicle_cat_name_idx"),
                    models.Index(fields=["is_active"], name="vehicle_cat_active_idx"),
                    models.Index(fields=["daily_rate"], name="vehicle_cat_daily_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("daily_rate__gte", 0)),
                        name="vehicle_cat_daily_rate_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("hourly_rate__isnull", True),
                            ("hourly_rate__gte", 0),
                            _connector="OR",
                        ),
                        name="vehicle_cat_hourly_rate_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("minimum_deposit__gte", 0)),
                        name="vehicle_cat_deposit_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("minimum_rental_hours__gt", 0)),
                        name="vehicle_cat_min_hours_positive",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ParkingSpace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spaces",
                        to="vehicles.parking",
                    ),
                ),
            ],
            options={
                "ordering": ["parking__name", "number"],
                "indexes": [
                    models.Index(fields=["parking"], name="parking_space_parking_idx"),
                    models.Index(fields=["number"], name="parking_space_number_idx"),
                    models.Index(fields=["is_active"], name="parking_space_active_idx"),
                    models.Index(
                        fields=["parking", "number"], name="parking_space_pk_num_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("parking", "number"), name="parking_space_unique_number"
                    )
                ],
            },
        ),
    ]
