# Generated by Django 6.0.7 on 2026-08-01 00:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_number", models.CharField(max_length=30, unique=True)),
                ("model_name", models.CharField(max_length=150)),
                (
                    "year",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1886)]
                    ),
                ),
                ("color", models.CharField(max_length=60)),
                ("energy_type", models.CharField(max_length=60)),
                ("transmission", models.CharField(max_length=60)),
                (
                    "seats",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "doors",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("mileage", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DISPONIBLE", "Disponible"),
                            ("RESERVE", "Reserve"),
                            ("LOUE", "Loue"),
                            ("A_CONTROLER", "A controler"),
                            ("MAINTENANCE", "Maintenance"),
                            ("NETTOYAGE", "Nettoyage"),
                            ("ACCIDENTE", "Accidente"),
                            ("INDISPONIBLE", "Indisponible"),
                        ],
                        default="DISPONIBLE",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehicles",
                        to="vehicles.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehicles",
                        to="vehicles.vehiclecategory",
                    ),
                ),
                (
                    "parking_space",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehicle",
                        to="vehicles.parkingspace",
                    ),
                ),
            ],
            options={
                "ordering": ["brand__name", "model_name", "registration_number"],
            },
        ),
        migrations.CreateModel(
            name="VehiclePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.ImageField(upload_to="vehicles/photos/")),
                ("is_primary", models.BooleanField(default=False)),
                ("position", models.PositiveIntegerField(default=0)),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "position", "created_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(fields=["status"], name="vehicle_status_idx"),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(fields=["category"], name="vehicle_category_idx"),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(fields=["brand"], name="vehicle_brand_idx"),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(fields=["is_active"], name="vehicle_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="vehicle",
            constraint=models.CheckConstraint(
                condition=models.Q(("seats__gt", 0)), name="vehicle_seats_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="vehicle",
            constraint=models.CheckConstraint(
                condition=models.Q(("doors__gt", 0)), name="vehicle_doors_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="vehicle",
            constraint=models.CheckConstraint(
                condition=models.Q(("mileage__gte", 0)),
                name="vehicle_mileage_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="vehiclephoto",
            index=models.Index(fields=["vehicle"], name="vehicle_photo_vehicle_idx"),
        ),
        migrations.AddIndex(
            model_name="vehiclephoto",
            index=models.Index(fields=["is_primary"], name="vehicle_photo_primary_idx"),
        ),
        migrations.AddIndex(
            model_name="vehiclephoto",
            index=models.Index(fields=["position"], name="vehicle_photo_position_idx"),
        ),
    ]
