# Generated by Django 6.0.7 on 2026-08-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0004_seed_vehicle_equipment_catalog"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="recommended_use",
            field=models.TextField(blank=True),
        ),
    ]
