# Generated by Django 6.0.7 on 2026-09-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_vehicle_recommended_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='needs_supervision',
            field=models.BooleanField(default=False, help_text='Signale une anomalie ACCEPTABLE relevee au check-in : le vehicule reste utilisable mais doit etre surveille par le gestionnaire.'),
        ),
    ]
