# Generated by Django 6.0.7 on 2026-09-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_vehicle_needs_supervision'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='has_urgent_checkin_anomaly',
            field=models.BooleanField(default=False, help_text="Signale que le statut A_CONTROLER provient d'une anomalie GRAVE relevee au check-in client."),
        ),
    ]
