export { default as Hero } from './Hero'
export { default as SearchSection } from './SearchSection'
export { default as HowItWorks } from './HowItWorks'
export { default as Advantages } from './Advantages'
export { default as PopularVehicles } from './PopularVehicles'
export { default as FaqSection } from './FaqSection'
export { default as CallToAction } from './CallToAction'
