# Generated by Django 6.0.7 on 2026-08-01 09:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "accounts",
            "0002_remove_clientdocument_uniq_active_doc_per_client_type_and_more",
        ),
        ("vehicles", "0002_vehicle_vehiclephoto_vehicle_vehicle_status_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        editable=False,
                        help_text="Reference generee automatiquement par le backend.",
                        max_length=16,
                        unique=True,
                    ),
                ),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("EN_ATTENTE_CAUTION", "En attente caution"),
                            ("EN_ATTENTE_PAIEMENT", "En attente paiement"),
                            ("CONFIRMEE", "Confirmee"),
                            ("EN_COURS", "En cours"),
                            ("A_CONTROLER", "A controler"),
                            ("TERMINEE", "Terminee"),
                            ("ANNULEE", "Annulee"),
                            ("PAIEMENT_ECHOUE", "Paiement echoue"),
                        ],
                        default="BROUILLON",
                        max_length=24,
                    ),
                ),
                (
                    "rental_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="accounts.clientprofile",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["client", "status"],
                        name="reservation_client_status_idx",
                    ),
                    models.Index(
                        fields=["vehicle", "status"],
                        name="reservation_vehicle_status_idx",
                    ),
                    models.Index(
                        fields=["start_at", "end_at"], name="reservation_period_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="reservation_created_at_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_at__gt", models.F("start_at"))),
                        name="reservation_end_after_start",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("rental_amount__gte", 0)),
                        name="reservation_rental_amount_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("deposit_amount__gte", 0)),
                        name="reservation_deposit_amount_non_negative",
                    ),
                ],
            },
        ),
    ]
