# Generated by Django 6.0.7 on 2026-09-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_insurance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE_CAUTION', 'En attente caution'), ('EN_ATTENTE_PAIEMENT', 'En attente paiement'), ('CONFIRMEE', 'Confirmee'), ('REAFFECTATION_REQUIRED', 'A reaffecter'), ('EN_COURS', 'En cours'), ('A_CONTROLER', 'A controler'), ('TERMINEE', 'Terminee'), ('ANNULEE', 'Annulee'), ('PAIEMENT_ECHOUE', 'Paiement echoue')], default='BROUILLON', max_length=24),
        ),
    ]
