# Generated by Django 6.0.7 on 2026-09-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='review_resolved_at',
            field=models.DateTimeField(blank=True, help_text="Date a laquelle un gestionnaire a resolu l'indicateur d'anomalie au check-in (badge 'A verifier').", null=True),
        ),
    ]
