# Generated by Django 6.0.7 on 2026-08-03 09:30

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reservations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("STRIPE", "Stripe")], default="STRIPE", max_length=20
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="EUR", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREE", "Cree"),
                            ("EN_ATTENTE", "En attente"),
                            ("ACTION_REQUISE", "Action requise"),
                            ("TRAITEMENT", "Traitement"),
                            ("REUSSI", "Reussi"),
                            ("ECHOUE", "Echoue"),
                            ("ANNULE", "Annule"),
                        ],
                        db_index=True,
                        default="CREE",
                        max_length=20,
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "failure_code",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("failure_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("succeeded_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="reservations.reservation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="EUR", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DEMANDE", "Demande"),
                            ("EN_COURS", "En cours"),
                            ("REUSSI", "Reussi"),
                            ("ECHOUE", "Echoue"),
                            ("ANNULE", "Annule"),
                        ],
                        db_index=True,
                        default="DEMANDE",
                        max_length=20,
                    ),
                ),
                (
                    "stripe_refund_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("succeeded_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refunds",
                        to="payments.payment",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_refunds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refunds",
                        to="reservations.reservation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StripeEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stripe_event_id", models.CharField(max_length=255, unique=True)),
                ("event_type", models.CharField(db_index=True, max_length=255)),
                ("api_version", models.CharField(blank=True, max_length=50, null=True)),
                ("payload", models.JSONField()),
                ("processed", models.BooleanField(db_index=True, default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("processing_error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["stripe_event_id"], name="se_event_id_idx"),
                    models.Index(fields=["event_type"], name="se_type_idx"),
                    models.Index(fields=["processed"], name="se_processed_idx"),
                    models.Index(fields=["created_at"], name="se_created_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Deposit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("SIMULATED", "Simulated"),
                            ("STRIPE_TEST", "Stripe test"),
                        ],
                        default="SIMULATED",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="EUR", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREE", "Cree"),
                            ("EN_ATTENTE", "En attente"),
                            ("AUTORISEE", "Autorisee"),
                            ("CAPTUREE", "Capturee"),
                            ("LIBEREE", "Liberee"),
                            ("ECHOUEE", "Echouee"),
                            ("ANNULEE", "Annulee"),
                            ("EXPIREE", "Expiree"),
                        ],
                        db_index=True,
                        default="CREE",
                        max_length=20,
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "authorization_expires_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("authorized_at", models.DateTimeField(blank=True, null=True)),
                ("captured_at", models.DateTimeField(blank=True, null=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deposits",
                        to="reservations.reservation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["reservation"], name="dep_reservation_idx"),
                    models.Index(fields=["status"], name="dep_status_idx"),
                    models.Index(
                        fields=["stripe_payment_intent_id"], name="dep_pi_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gte", 0)), name="dep_amount_gte_0"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "currency",
                                django.db.models.functions.text.Upper("currency"),
                            )
                        ),
                        name="dep_currency_upper",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["reservation"], name="pay_reservation_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["status"], name="pay_status_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["stripe_payment_intent_id"], name="pay_pi_idx"),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)), name="pay_amount_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("currency", django.db.models.functions.text.Upper("currency"))
                ),
                name="pay_currency_upper",
            ),
        ),
        migrations.AddIndex(
            model_name="refund",
            index=models.Index(fields=["payment"], name="ref_payment_idx"),
        ),
        migrations.AddIndex(
            model_name="refund",
            index=models.Index(fields=["reservation"], name="ref_reservation_idx"),
        ),
        migrations.AddIndex(
            model_name="refund",
            index=models.Index(fields=["status"], name="ref_status_idx"),
        ),
        migrations.AddIndex(
            model_name="refund",
            index=models.Index(fields=["stripe_refund_id"], name="ref_stripe_id_idx"),
        ),
        migrations.AddConstraint(
            model_name="refund",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)), name="ref_amount_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="refund",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("currency", django.db.models.functions.text.Upper("currency"))
                ),
                name="ref_currency_upper",
            ),
        ),
    ]
