# Generated by Django 6.0.7 on 2026-08-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deposit",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREE", "Cree"),
                    ("EN_ATTENTE", "En attente"),
                    ("AUTORISEE", "Autorisee"),
                    ("A_VERIFIER", "A verifier"),
                    ("CAPTUREE", "Capturee"),
                    ("LIBEREE", "Liberee"),
                    ("ECHOUEE", "Echouee"),
                    ("ANNULEE", "Annulee"),
                    ("EXPIREE", "Expiree"),
                ],
                db_index=True,
                default="CREE",
                max_length=20,
            ),
        ),
    ]
