# Generated by Django 6.0.7 on 2026-08-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EN_COURS", "En cours"),
                            ("REUSSIE", "Reussie"),
                            ("ECHEC", "Echec"),
                        ],
                        default="EN_COURS",
                        max_length=20,
                    ),
                ),
                (
                    "backup_type",
                    models.CharField(
                        choices=[("DATABASE", "Database")],
                        default="DATABASE",
                        max_length=20,
                    ),
                ),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("file_path", models.TextField()),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
