# Generated by Django 6.0.7 on 2026-08-03 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reservations", "0001_initial"),
        ("vehicles", "0002_vehicle_vehiclephoto_vehicle_vehicle_status_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACTIVE", "Active"),
                            ("REVOKED", "Revoked"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "lock_state",
                    models.CharField(
                        choices=[("LOCKED", "Locked"), ("UNLOCKED", "Unlocked")],
                        default="LOCKED",
                        max_length=16,
                    ),
                ),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("last_unlocked_at", models.DateTimeField(blank=True, null=True)),
                ("last_locked_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehicle_accesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reservation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehicle_access",
                        to="reservations.reservation",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="access_records",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="LockingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("UNLOCK", "Unlock"),
                            ("LOCK", "Lock"),
                            ("ACCESS_ACTIVATED", "Access activated"),
                            ("ACCESS_REVOKED", "Access revoked"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[("SUCCESS", "Success"), ("FAILURE", "Failure")],
                        max_length=10,
                    ),
                ),
                (
                    "failure_code",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("failure_message", models.TextField(blank=True, null=True)),
                (
                    "attempted_reservation_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=512, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locking_logs",
                        to="reservations.reservation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locking_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locking_logs",
                        to="vehicles.vehicle",
                    ),
                ),
                (
                    "vehicle_access",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locking_logs",
                        to="interventions.vehicleaccess",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="vehicleaccess",
            index=models.Index(fields=["status"], name="veh_access_status_idx"),
        ),
        migrations.AddIndex(
            model_name="vehicleaccess",
            index=models.Index(fields=["is_active"], name="veh_access_is_active_idx"),
        ),
        migrations.AddIndex(
            model_name="vehicleaccess",
            index=models.Index(fields=["valid_from"], name="veh_access_valid_from_idx"),
        ),
        migrations.AddIndex(
            model_name="vehicleaccess",
            index=models.Index(
                fields=["valid_until"], name="veh_access_valid_until_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicleaccess",
            index=models.Index(
                fields=["vehicle", "is_active"], name="veh_access_vehicle_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lockinglog",
            index=models.Index(
                fields=["reservation", "created_at"], name="lock_log_res_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lockinglog",
            index=models.Index(
                fields=["vehicle", "created_at"], name="lock_log_veh_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lockinglog",
            index=models.Index(
                fields=["user", "created_at"], name="lock_log_user_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lockinglog",
            index=models.Index(
                fields=["action", "result"], name="lock_log_action_result_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lockinglog",
            index=models.Index(fields=["created_at"], name="lock_log_created_at_idx"),
        ),
    ]
