# Generated by Django 6.0.7 on 2026-08-03 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspections", "0002_damage_evidence_photos"),
        ("interventions", "0001_initial"),
        ("reservations", "0001_initial"),
        ("vehicles", "0002_vehicle_vehiclephoto_vehicle_vehicle_status_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Intervention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=40, unique=True)),
                (
                    "intervention_type",
                    models.CharField(
                        choices=[
                            ("MECANIQUE", "Mecanique"),
                            ("NETTOYAGE", "Nettoyage"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("A_ATTRIBUER", "A attribuer"),
                            ("ATTRIBUEE", "Attribuee"),
                            ("EN_COURS", "En cours"),
                            ("TERMINEE", "Terminee"),
                            ("ANNULEE", "Annulee"),
                        ],
                        default="A_ATTRIBUER",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("report", models.TextField(blank=True)),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "final_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_interventions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_interventions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inspection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interventions",
                        to="inspections.inspection",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interventions",
                        to="reservations.reservation",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="interventions",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TechnicalInspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mileage", models.PositiveIntegerField()),
                ("energy_level_percent", models.PositiveSmallIntegerField()),
                ("observations", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "intervention",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technical_inspections",
                        to="interventions.intervention",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="technical_inspections",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TechnicalPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.ImageField(upload_to="technical_inspections/photos/")),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "technical_inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="interventions.technicalinspection",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="intervention",
            index=models.Index(fields=["reference"], name="interv_reference_idx"),
        ),
        migrations.AddIndex(
            model_name="intervention",
            index=models.Index(fields=["status"], name="interv_status_idx"),
        ),
        migrations.AddIndex(
            model_name="intervention",
            index=models.Index(fields=["intervention_type"], name="interv_type_idx"),
        ),
        migrations.AddIndex(
            model_name="intervention",
            index=models.Index(
                fields=["vehicle", "status"], name="interv_vehicle_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="intervention",
            index=models.Index(
                fields=["assigned_to", "status"], name="interv_assignee_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="intervention",
            index=models.Index(fields=["reservation"], name="interv_reservation_idx"),
        ),
        migrations.AddConstraint(
            model_name="intervention",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("estimated_cost__gte", 0),
                    ("estimated_cost__isnull", True),
                    _connector="OR",
                ),
                name="interv_estimated_cost_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="intervention",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("final_cost__gte", 0),
                    ("final_cost__isnull", True),
                    _connector="OR",
                ),
                name="interv_final_cost_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="intervention",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("completed_at__isnull", True),
                    ("status", "TERMINEE"),
                    _connector="OR",
                ),
                name="interv_completed_at_only_done",
            ),
        ),
        migrations.AddConstraint(
            model_name="intervention",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("started_at__isnull", True),
                    ("status", "EN_COURS"),
                    _connector="OR",
                ),
                name="interv_started_at_only_in_progress",
            ),
        ),
        migrations.AddConstraint(
            model_name="intervention",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "A_ATTRIBUER"),
                    ("assigned_to__isnull", False),
                    _connector="OR",
                ),
                name="interv_assigned_required_unless_to_assign",
            ),
        ),
        migrations.AddIndex(
            model_name="technicalinspection",
            index=models.Index(
                fields=["intervention"], name="tech_insp_intervention_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="technicalinspection",
            index=models.Index(fields=["vehicle"], name="tech_insp_vehicle_idx"),
        ),
        migrations.AddIndex(
            model_name="technicalinspection",
            index=models.Index(fields=["created_at"], name="tech_insp_created_at_idx"),
        ),
        migrations.AddConstraint(
            model_name="technicalinspection",
            constraint=models.CheckConstraint(
                condition=models.Q(("mileage__gte", 0)), name="tech_insp_mileage_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="technicalinspection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("energy_level_percent__gte", 0), ("energy_level_percent__lte", 100)
                ),
                name="tech_insp_energy_0_100",
            ),
        ),
        migrations.AddIndex(
            model_name="technicalphoto",
            index=models.Index(
                fields=["technical_inspection"], name="tech_photo_insp_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="technicalphoto",
            index=models.Index(fields=["created_at"], name="tech_photo_created_at_idx"),
        ),
    ]
