# Generated by Django 6.0.7 on 2026-08-07 08:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspections", "0002_damage_evidence_photos"),
        (
            "interventions",
            "0002_intervention_technicalinspection_technicalphoto_and_more",
        ),
        ("reservations", "0001_initial"),
        ("vehicles", "0002_vehicle_vehiclephoto_vehicle_vehicle_status_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="intervention",
            name="interv_started_at_only_in_progress",
        ),
        migrations.AddConstraint(
            model_name="intervention",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("started_at__isnull", True),
                        ("status__in", ["A_ATTRIBUER", "ATTRIBUEE", "ANNULEE"]),
                    ),
                    models.Q(
                        ("started_at__isnull", False),
                        ("status__in", ["EN_COURS", "TERMINEE"]),
                    ),
                    _connector="OR",
                ),
                name="interv_started_at_only_in_progress",
            ),
        ),
    ]
