# Generated by Django 6.0.7 on 2026-09-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0004_technicalinspection_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='planned_end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='planned_start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
