# Generated by Django 6.0.7 on 2026-09-24 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0005_intervention_planned_end_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervention_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='intervention',
            name='decision',
            field=models.CharField(blank=True, choices=[('RETURN_TO_PARK', 'Remis au parc'), ('MARK_UNAVAILABLE', 'Rendu indisponible'), ('PLAN_MAINTENANCE', 'Nouvelle maintenance planifiée'), ('PLAN_CLEANING', 'Nouveau nettoyage planifié')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='decision_comment',
            field=models.TextField(blank=True),
        ),
    ]
