# Generated by Django 6.0.7 on 2026-09-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interventions", "0006_intervention_decided_at_intervention_decided_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intervention",
            name="status",
            field=models.CharField(
                choices=[
                    ("A_ATTRIBUER", "A attribuer"),
                    ("ATTRIBUEE", "Attribuee"),
                    ("EN_COURS", "En cours"),
                    ("EN_PAUSE", "En pause"),
                    ("TERMINEE", "Terminee"),
                    ("ANNULEE", "Annulee"),
                ],
                default="A_ATTRIBUER",
                max_length=20,
            ),
        ),
        migrations.RemoveConstraint(
            model_name="intervention",
            name="interv_started_at_only_in_progress",
        ),
        migrations.AddConstraint(
            model_name="intervention",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        models.Q(
                            ("started_at__isnull", True),
                            ("status__in", ["A_ATTRIBUER", "ATTRIBUEE", "ANNULEE"]),
                        ),
                        models.Q(
                            ("started_at__isnull", False),
                            ("status__in", ["EN_COURS", "EN_PAUSE", "TERMINEE"]),
                        ),
                        _connector="OR",
                    )
                ),
                name="interv_started_at_only_in_progress",
            ),
        ),
    ]