# Generated by Django 6.0.7 on 2026-09-24 20:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_allow_interieur_positions'),
        ('interventions', '0007_add_intervention_paused_status'),
        ('reservations', '0003_alter_reservation_status'),
        ('vehicles', '0005_vehicle_recommended_use'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='intervention',
            name='interv_started_at_only_in_progress',
        ),
        migrations.AlterField(
            model_name='intervention',
            name='status',
            field=models.CharField(choices=[('A_ATTRIBUER', 'A attribuer'), ('ATTRIBUEE', 'Attribuee'), ('PLANIFIEE', 'Planifiee'), ('EN_COURS', 'En cours'), ('EN_PAUSE', 'En pause'), ('TERMINEE', 'Terminee'), ('ANNULEE', 'Annulee')], default='A_ATTRIBUER', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='intervention',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('started_at__isnull', True), ('status__in', ['A_ATTRIBUER', 'ATTRIBUEE', 'PLANIFIEE', 'ANNULEE'])), models.Q(('started_at__isnull', False), ('status__in', ['EN_COURS', 'EN_PAUSE', 'TERMINEE'])), _connector='OR'), name='interv_started_at_only_in_progress'),
        ),
    ]
