# Generated by Django 6.0.7 on 2026-09-24 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0008_remove_intervention_interv_started_at_only_in_progress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionWorkPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_periods', to='interventions.intervention')),
            ],
            options={
                'ordering': ['started_at', 'id'],
                'indexes': [models.Index(fields=['intervention', 'started_at'], name='interv_work_period_start_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='interv_work_period_end_after_start'), models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('intervention',), name='interv_one_open_work_period')],
            },
        ),
    ]
